In [1]:
import numpy as np
import pandas as pd

## create a 3*3*3 array with random values

In [8]:
np.random.randint(200,size=(3,3,3))

array([[[ 92,  47, 174],
        [ 53, 159,  26],
        [166, 104, 154]],

       [[  8,  57, 127],
        [ 78, 125, 160],
        [187,  32,  82]],

       [[ 37, 182,  92],
        [190, 143,  56],
        [186, 148, 116]]])

## create 5*5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
mat = np.random.randint(low=1,high=5,size=(5,5))
lower_mat = np.tril(mat,k=-1)
lower_mat

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [2, 1, 0, 0, 0],
       [1, 3, 2, 0, 0],
       [4, 4, 3, 1, 0]])

## create 8*8 matrix and fill it with a check board pattern

In [23]:
zeros = np.zeros((8,8),dtype=int)
zeros[1::2,::2] = 1 
zeros[::2,1::2] = 1
zeros

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## normalize a 5*5 random matrix

In [29]:
mt = np.random.random(size=(5,5))
print("Before Normalize ")
print(mt)

print('After Normalize:')
mt_min, mt_max = mt.min(), mt.max()

mt = (mt - mt_min)/(mt_max - mt_min)
print(mt)

Before Normalize 
[[0.724638   0.24479395 0.72032195 0.1213317  0.46874671]
 [0.99000425 0.34116279 0.94944313 0.77280776 0.82892136]
 [0.02444033 0.32246865 0.39270883 0.24772004 0.38613002]
 [0.49577648 0.6274368  0.27975526 0.13369288 0.49827524]
 [0.34231287 0.15051845 0.29938478 0.88594927 0.48873457]]
After Normalize:
[[0.72516968 0.22821237 0.72069969 0.10034693 0.46015223]
 [1.         0.32801813 0.9579923  0.77505737 0.83317222]
 [0.         0.30865727 0.38140251 0.23124281 0.37458907]
 [0.48814598 0.62450186 0.26442054 0.11314896 0.49073387]
 [0.32920922 0.13057461 0.28475013 0.89223399 0.48085293]]


## how to find common values between two arrays

In [12]:
a = np.random.randint(10,size=(10))
b = np.random.randint(10,size=(10))
print('Matrix :A',a)
print('Matrix :B',b)
print('Common values:',np.intersect1d(a,b))

Matrix :A [3 7 6 7 7 4 8 4 7 1]
Matrix :B [6 5 4 3 9 7 0 5 2 4]
Common values: [3 4 6 7]


## how to get the dates of yesterday,today and tommorow

In [13]:
import numpy as np
yesterday_date = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday_date)
today_date = np.datetime64('today', 'D')
print("Today    : ",today_date)
tomorrow_date = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow : ",tomorrow_date)

Yestraday:  2020-07-25
Today    :  2020-07-26
Tomorrow :  2020-07-27


## consider two random arrays A anb B check if they are equal

In [14]:
A = np.random.random((2, 2))
B = np.random.random((2, 2))
print("A")
print(A)
print("B")
print(B)
check_equal = np.allclose(A, B)
if check_equal == True:
    print("\nA and B Matrix are equal")
else:
    print("\nA and B Matrix are Not equal")

A
[[0.1129349  0.90913879]
 [0.59359237 0.72831579]]
B
[[0.96669451 0.66841207]
 [0.73034859 0.85056979]]

A and B Matrix are Not equal


## create random vectors of size 10 and replace the maximum value by 0

In [15]:
mat = np.random.randint(10,size=(10))
print("Random Matrix")
print(mat)
print("After Replacing Max value by 0")
print("Maximum value :",np.amax(mat))
print(np.where(mat ==np.amax(mat),0,mat))

Random Matrix
[1 2 6 5 1 1 3 3 5 8]
After Replacing Max value by 0
Maximum value : 8
[1 2 6 5 1 1 3 3 5 0]


## how to print all the values of array

In [16]:
arr = np.random.randint(10,size=(4,4))
print(arr)
print("\\\ All Values of array //")
for i in range(0,len(arr)):
    for j in range(arr.shape[1]):
        print(arr[i][j],end=' ')

[[3 2 6 4]
 [5 5 1 9]
 [6 9 8 3]
 [7 8 6 2]]
\\ All Values of array //
3 2 6 4 5 5 1 9 6 9 8 3 7 8 6 2 

## subract the mean of each rows of a matrix

In [17]:
print("Original matrix:\n")
mat = np.random.randint(10,size=(2,2))
print(mat)
print("\nSubtract the mean of each row:\n")
sub = mat - mat.mean(axis=1, keepdims=True)
print(sub)

Original matrix:

[[7 1]
 [7 6]]

Subtract the mean of each row:

[[ 3.  -3. ]
 [ 0.5 -0.5]]


## How to get the diagonal of the dot product

In [18]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
ab = np.dot(A, B)
print("Dot product Matrix \n")
print(ab)
print()
print("Diagonal\n")
print(np.diag(ab))

Dot product Matrix 

[[22 56 58]
 [74 46 80]
 [24 50 53]]

Diagonal

[22 46 53]


## how to find the most frequent value in array

In [30]:
m = np.random.randint(0,100,100)
print (m)
print('Frequent Number:', np.bincount(m).argmax())

[35  5 15 45  5 82  7 27 56  8 22 37 21 24  7 64 38 53 46 24 41 56 20 44
 30 30 67 97  0 54 14 94 10 38 97 49 34 71 49 25 29 80 91 60 48 32 39 63
  8 91 93 96  8 29 30 10 76 42 74 29 19 55 57 64  2  9  1 55 81 10 13 66
 82 43 61  0 95 98 67 84 55 16 12 34 87 54 49  4 19 69 12 67 22 28 71 87
 27 94 28 83]
Frequent Number: 8


## How to create a record array from a regular array?¶

In [32]:
a = np.array([("python", 2.5, 3),
              ("hacker", 3.6, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
b

rec.array([(b'python', 2.5, 3), (b'hacker', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])