In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
df= pd.read_csv(r'C:/Users/ELCOT/Desktop/LU/train.csv')
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [3]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [11]:
encoder = LabelEncoder()
df.Sex = encoder.fit_transform(df['Sex'])
df.Embarked = encoder.fit_transform(df['Embarked'])

In [19]:
def naive_base(X,y):
    X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                test_size=0.2,
                                                random_state=3,)
    clf = BernoulliNB()
    clf.fit(X_train,y_train)
    y_preds = clf.predict(X_test)
    return confusion_matrix(y_test,y_preds),accuracy_score(y_test,y_preds)

In [20]:

naive_base(X=df.drop('Pclass',axis=1),y=pd.DataFrame(df['Pclass']))

C:\Users\ELCOT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([[11,  2, 22],
        [16,  1, 23],
        [22,  2, 79]], dtype=int64),
 0.5112359550561798)

In [21]:
naive_base(X=df.drop('Sex',axis=1),y=pd.DataFrame(df['Sex']))

C:\Users\ELCOT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([[ 40,   9],
        [ 27, 102]], dtype=int64),
 0.797752808988764)

In [22]:
naive_base(X=df.drop('SibSp',axis=1),y=pd.DataFrame(df['SibSp']))

C:\Users\ELCOT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([[111,  11,   0,   0,   0,   0],
        [ 29,  12,   0,   0,   0,   0],
        [  4,   3,   0,   0,   0,   0],
        [  3,   0,   0,   0,   0,   0],
        [  3,   1,   0,   0,   0,   0],
        [  1,   0,   0,   0,   0,   0]], dtype=int64),
 0.6910112359550562)

In [23]:
naive_base(X=df.drop('Parch',axis=1),y=pd.DataFrame(df['Parch']))

C:\Users\ELCOT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([[127,  10,   0,   0,   0],
        [ 17,   6,   0,   0,   0],
        [ 12,   3,   0,   0,   0],
        [  1,   0,   0,   0,   0],
        [  2,   0,   0,   0,   0]], dtype=int64),
 0.7471910112359551)

In [24]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [25]:
naive_base(X=df.drop('Embarked',axis=1),y=pd.DataFrame(df['Embarked']))

C:\Users\ELCOT\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([[  0,   0,  31],
        [  0,   0,  16],
        [  0,   0, 131]], dtype=int64),
 0.7359550561797753)